import Intro from '@/components/landing/Intro';
import About from '@/components/landing/About';
import StudentFeatures from '@/components/landing/StudentFeatures';
import PublicLayout from '@/layouts/PublicLayout';
import Head from 'next/head';
import ReactDOM from 'react-dom';

export default function Home() {
	return (
		<>
			<Head>
				<title>Easy Pay SRM</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<PublicLayout>
				<Intro />
				<About />
				<StudentFeatures />
			</PublicLayout>
		</>
	);
}
